- pkg/trisa/crypto/aesgcm/aesgcm.go
- pkg/trisa/crypto/aesgcm/aesgcm_test.go
- pkg/trisa/crypto/crypto.go
- pkg/trisa/crypto/rsaoeap/rsaoeap.go
- pkg/trisa/crypto/rsaoeap/rsaoeap_test.go
In this PR, I've started transferring over the original TRISA library code with modifications to enable the protocol at both ends and to make it simpler to replace the trisacrypto/trisa repository with this repository. 
So far:
- The trisa/crypto package has been moved over with stronger support for the `Crypto` interface (formerly `Handler`) and breaking out the `Cipher` and `Signer` interfaces for TRISA use.
> Crypto Package

- web/demo/npm/src/App.js
If you want to conslidate demo.alice.vaspbot.net and demo.bob.vaspbot.net -> demo.vaspbot.net, you can just update this change to have the new host name.  Otherwise, this should work with the existing deployment once deployed (and it'll only use bob).
> Point the react app to the deployed bff instance

- web/demo/bff/flaskr/service/socket_manager.py
- web/demo/npm/src/App.js
- web/demo/npm/src/services/VaspStreamingService.ts
Resolve issues with websockets not being cleared properly (and thus RVASP GRPC stream not being closed) after being cleared from the demo UI.
Also generates a new uuid for client name whenever an RVASP API instance is created
> Demo cleanup websockets

- docs/content/integration/_index.md
This PR updates the documentation about the TRIXO form completion stage, providing a blank, annotated JSON-like text snippet to illustrate what each of the fields expects in terms of values. I extracted the input details from the protocol buffers in the [`/proto` folder](https://github.com/trisacrypto/testnet/tree/main/proto).
> Updates TRIXO form sample with annotated JSON-like text

- containers/docs-redirect/Dockerfile
- containers/docs-redirect/nginx.conf
- manifests/docs.yaml
- skaffold.yaml
Implements an nginx Docker container that permanently redirects everything to trisa.dev and includes any paths in the redirect via rewrite rules. Sort of a heavyweight way to redirect, but effective and easy to deploy.
> trisatest.net docs redirect to trisa.dev

- pkg/rvasp/rvasp.go
- pkg/rvasp/trisa.go
This updates the rVASP transfer code to use the new envelope package rather than the old handler one.
> sc-5120 use new envelope package

- cmd/rvasp/main.go
- pkg/rvasp/db/db.go
- pkg/rvasp/db/db_test.go
- pkg/rvasp/db/fixtures.go
- pkg/rvasp/db/fixtures_test.go
- pkg/rvasp/rvasp.go
- pkg/rvasp/trisa.go
This unifies the database accesses by adding foreign key fields to the database tables which reference a VASP ID, which makes it possible to have multiple rvasps access the database at once. Along with this change is a refactor which puts the database-related code into its own `db` package, to make it easier to enforce the tenancy restraints.
> sc-5111 Multi-tenant database

- containers/db/reset/Dockerfile
- scripts/reset-db.sh
This adds a database reset job that can be run as a Docker container. It requires at least two environment variables to be passed into the container: `RVASP_DATABASE` which is the dsn pointing to the running postgres database and `RVASP_FIXTURES_PATH` which is the path to the database fixtures (should be set to `/fixtures`).
> sc-5110 Add database reset job

- go.mod
- go.sum
- pkg/rvasp/db/db.go
- pkg/rvasp/db/db_test.go
- pkg/rvasp/db/mock.go
This updates the database package tests to use the `sqlmock` package. This allows us to verify that our high-level database interactions are generating the queries we expect.
> sc-5572 database package tests

- cmd/rvasp/main.go
- pkg/rvasp/async.go
- pkg/rvasp/config/config.go
- pkg/rvasp/db/db.go
- pkg/rvasp/rvasp.go
- pkg/rvasp/trisa.go
This adds an async handler which can be run as a go routine and periodically checks pending transactions, performing transfers back to the originator to fulfill the protocol and marking the transactions as completed in the database.
> sc-5666 Add async handler

- pkg/rvasp/db/db.go
- pkg/rvasp/db/db_test.go
- pkg/rvasp/db/fixtures.go
- pkg/rvasp/fixtures/wallets.json
- pkg/rvasp/rvasp.go
This implements the policy decisions for the originator side by storing the configured policies in the `wallets` table, and calling the appropriate handler based on the wallet lookup at the beginning of `Transfer`.
> sc-5118 originator policy decisions

- pkg/rvasp/trisa.go
This adds policy decisions for the beneficiary rVASP similar to what was just done for the originator, so that the beneficiary executes the appropriate scenario depending on the beneficiary wallet address specified in the transaction.
> sc-5119 Add beneficiary policy decisions

- pkg/rvasp/rvasp.go
- pkg/rvasp/transfer.go
- pkg/rvasp/trisa.go
This implements the policy functions on the originator side and does some refactoring to reduce common code. The `full_async` and `rejected_async` functions are partially implemented at the moment; some work needs to be done on the beneficiary side to send the pending message to the originator. This is also missing the last part of the originator asynchronous code which responds to the messages from the beneficiary go routine in `async.go`. These parts will be implemented in another PR.
> sc-5664 Implement originator policy functions

- .github/workflows/release.yml
- .goreleaser.yml
This adds the goreleaser GitHub action to publish releases of the rVASP program.
> sc-5117 Add goreleaser

- scripts/rvasp-test.sh
This script executes several rVASP commands in a row in meaningful combinations between Alice and Bob as a quick check to ensure the rVASPs are up and running.
> rVASP Test Script

- .github/workflows/containers.yml
This adds a containers build and push action so that images are automatically built with on PRs and pushed on tags.
> sc-6368 Add containers action

- pkg/rvasp/db/db.go
- pkg/rvasp/fixtures/wallets.json
- pkg/rvasp/rvasp.go
- pkg/rvasp/trisa.go
- scripts/rvasp-test.sh
This marshals the `generic.Transaction` payload as a string to the database in a similar manner to how we're handling the identity payload. This allows us to avoid having to reconstruct the payload for async transactions so the rvasps can act a bit more consistent. I also discovered some bugs in local testing which I've taken the opportunity to fix.
> sc-5933 Marshal transaction

- pkg/rvasp/fixtures/vasps.json
- pkg/rvasp/fixtures/wallets.json
This PR updates the rVASP LegalPerson and NaturalPerson records for the rVASP business records and their "account holders" to allow it to match more closely with correct/expected IVMS101. 
@pdeziel is changing just these fixture files sufficient to have them be included in the next migration?
> Update rVASP IVMS 101

- containers/docker-compose.yml
- pkg/rvasp/mock.go
- pkg/rvasp/peer.go
- pkg/rvasp/rvasp.go
- pkg/rvasp/transfer.go
- pkg/rvasp/trisa.go
- pkg/rvasp/trisa_test.go
- scripts/fixtures/gds-fixture.py
- scripts/fixtures/rvasp-fixtures.py
- scripts/generate-fixtures.sh
This PR fixes SC-7143 and SC-7144. The rVASPs now check for existence of the endpoint on the peer before trying to do key exchanges or transfers, and use the peers cache instead of always performing the GDS lookups. This also cleans up a lot of the error handling by returning errors in the envelope instead of in the gRPC error.
> SC-7143 endpoint lookup and error handling

- go.mod
- go.sum
- pkg/rvasp/transfer.go
- pkg/rvasp/trisa.go
This fixes the identity payload validation so that the beneficiary fields are only checked on the "repair" policies, and also fixes the problem where a nil response was being returned to gRPC.
> SC-7278 fix identity validation

- pkg/rvasp/db/fixtures_test.go
- pkg/rvasp/rvasp.go
- pkg/rvasp/transfer.go
- pkg/rvasp/trisa.go
- pkg/rvasp/trisa_test.go
This fixes an rVASP -> rVASP issue concerning the `SyncRequire` policy.
On the originator side, the rVASP generates an identity payload with a non-nil (but empty) beneficiary identity. However, on the beneficiary side the rVASP validates that the beneficiary identity is non-nil. This was causing an issue on `SendPartial` -> `SyncRequire` because the originating rVASP is generating an empty payload but the beneficiary rVASP assumes this is valid.
To fix this, the validation check is improved to validate the actual fields within the beneficiary identity on the identity payload. The validation now uses the TRISA ivms methods to verify the `LegalPerson` (the beneficiary VASP) and `NaturalPerson` (the beneficiary account).
> SC-7425 Improve beneficiary identity check

- pkg/rvasp/rvasp.go
- pkg/rvasp/trisa.go
This populates the previously empty fields on the pending messages that the rVASP returns on async transfers.
> SC-8140 Add fields to pending payload

- pkg/rvasp/transfer.go
- pkg/rvasp/transfer_test.go
- pkg/rvasp/trisa.go
Adds tests for the transfer.go ValidateIdentityPayload method (and exports it so it can be tested).
> SC-14000 Add Identity Payload Validation Tests
